const COUNTRIES = [
  { Andorra: "AD", name: "Andorra" },
  { Albania: "AL", name: "Albania" },
  { Argentina: "AR", name: "Argentina" },
  { Austria: "AT", name: "Austria" },
  { Australia: "AU", name: "Australia" },
  { "Åland Islands": "AX", name: "Åland Islands" },
  { "Bosnia and Herzegovina": "BA", name: "Bosnia and Herzegovina" },
  { Barbados: "BB", name: "Barbados" },
  { Belgium: "BE", name: "Belgium" },
  { Bulgaria: "BG", name: "Bulgaria" },
  { Benin: "BJ", name: "Benin" },
  { Bolivia: "BO", name: "Bolivia" },
  { Brazil: "BR", name: "Brazil" },
  { Bahamas: "BS", name: "Bahamas" },
  { Botswana: "BW", name: "Botswana" },
  { Belarus: "BY", name: "Belarus" },
  { Belize: "BZ", name: "Belize" },
  { Canada: "CA", name: "Canada" },
  { Switzerland: "CH", name: "Switzerland" },
  { Chile: "CL", name: "Chile" },
  { China: "CN", name: "China" },
  { Colombia: "CO", name: "Colombia" },
  { "Costa Rica": "CR", name: "Costa Rica" },
  { Cuba: "CU", name: "Cuba" },
  { Cyprus: "CY", name: "Cyprus" },
  { Czechia: "CZ", name: "Czechia" },
  { Germany: "DE", name: "Germany" },
  { Denmark: "DK", name: "Denmark" },
  { "Dominican Republic": "DO", name: "Dominican Republic" },
  { Ecuador: "EC", name: "Ecuador" },
  { Estonia: "EE", name: "Estonia" },
  { Egypt: "EG", name: "Egypt" },
  { Spain: "ES", name: "Spain" },
  { Finland: "FI", name: "Finland" },
  { "Faroe Islands": "FO", name: "Faroe Islands" },
  { France: "FR", name: "France" },
  { Gabon: "GA", name: "Gabon" },
  { "United Kingdom": "GB", name: "United Kingdom" },
  { Grenada: "GD", name: "Grenada" },
  { Guernsey: "GG", name: "Guernsey" },
  { Gibraltar: "GI", name: "Gibraltar" },
  { Greenland: "GL", name: "Greenland" },
  { Gambia: "GM", name: "Gambia" },
  { Greece: "GR", name: "Greece" },
  { Guatemala: "GT", name: "Guatemala" },
  { Guyana: "GY", name: "Guyana" },
  { Honduras: "HN", name: "Honduras" },
  { Croatia: "HR", name: "Croatia" },
  { Haiti: "HT", name: "Haiti" },
  { Hungary: "HU", name: "Hungary" },
  { Indonesia: "ID", name: "Indonesia" },
  { Ireland: "IE", name: "Ireland" },
  { "Isle of Man": "IM", name: "Isle of Man" },
  { Iceland: "IS", name: "Iceland" },
  { Italy: "IT", name: "Italy" },
  { Jersey: "JE", name: "Jersey" },
  { Jamaica: "JM", name: "Jamaica" },
  { Japan: "JP", name: "Japan" },
  { "South Korea": "KR", name: "South Korea" },
  { Liechtenstein: "LI", name: "Liechtenstein" },
  { Lesotho: "LS", name: "Lesotho" },
  { Lithuania: "LT", name: "Lithuania" },
  { Luxembourg: "LU", name: "Luxembourg" },
  { Latvia: "LV", name: "Latvia" },
  { Morocco: "MA", name: "Morocco" },
  { Monaco: "MC", name: "Monaco" },
  { Moldova: "MD", name: "Moldova" },
  { Montenegro: "ME", name: "Montenegro" },
  { Madagascar: "MG", name: "Madagascar" },
  { "North Macedonia": "MK", name: "North Macedonia" },
  { Mongolia: "MN", name: "Mongolia" },
  { Montserrat: "MS", name: "Montserrat" },
  { Malta: "MT", name: "Malta" },
  { Mexico: "MX", name: "Mexico" },
  { Mozambique: "MZ", name: "Mozambique" },
  { Namibia: "NA", name: "Namibia" },
  { Niger: "NE", name: "Niger" },
  { Nigeria: "NG", name: "Nigeria" },
  { Nicaragua: "NI", name: "Nicaragua" },
  { Netherlands: "NL", name: "Netherlands" },
  { Norway: "NO", name: "Norway" },
  { "New Zealand": "NZ", name: "New Zealand" },
  { Panama: "PA", name: "Panama" },
  { Peru: "PE", name: "Peru" },
  { "Papua New Guinea": "PG", name: "Papua New Guinea" },
  { Poland: "PL", name: "Poland" },
  { "Puerto Rico": "PR", name: "Puerto Rico" },
  { Portugal: "PT", name: "Portugal" },
  { Paraguay: "PY", name: "Paraguay" },
  { Romania: "RO", name: "Romania" },
  { Serbia: "RS", name: "Serbia" },
  { Russia: "RU", name: "Russia" },
  { Sweden: "SE", name: "Sweden" },
  { Singapore: "SG", name: "Singapore" },
  { Slovenia: "SI", name: "Slovenia" },
  { "Svalbard and Jan Mayen": "SJ", name: "Svalbard and Jan Mayen" },
  { Slovakia: "SK", name: "Slovakia" },
  { "San Marino": "SM", name: "San Marino" },
  { Suriname: "SR", name: "Suriname" },
  { "El Salvador": "SV", name: "El Salvador" },
  { Tunisia: "TN", name: "Tunisia" },
  { Turkey: "TR", name: "Turkey" },
  { Ukraine: "UA", name: "Ukraine" },
  { "United States": "US", name: "United States" },
  { Uruguay: "UY", name: "Uruguay" },
  { "Vatican City": "VA", name: "Vatican City" },
  { Venezuela: "VE", name: "Venezuela" },
  { Vietnam: "VN", name: "Vietnam" },
  { "South Africa": "ZA", name: "South Africa" },
  { Zimbabwe: "ZW", name: "Zimbabwe" },
];

export default COUNTRIES;
